from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from datetime import datetime


def create_pdf(content):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        rightMargin=30,
        leftMargin=30,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "TitleStyle",
        parent=styles["Title"],
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        "HeadingStyle",
        parent=styles["Heading2"],
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = styles["BodyText"]

    story = []

    # Title
    story.append(
        Paragraph(
            "FitFusion AI - Personalized Fitness Plan",
            title_style
        )
    )

    story.append(Spacer(1, 10))

    # Date & Time
    story.append(
        Paragraph(
            f"Generated on: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            body_style
        )
    )

    story.append(Spacer(1, 15))

    lines = content.split("\n")

    for line in lines:

        line = line.strip()

        if not line:
            continue

        clean_line = (
            line.replace("##", "")
                .replace("###", "")
                .replace("**", "")
                .replace("--", "")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
        )

        if (
            "Fitness Assessment" in clean_line
            or "Workout Plan" in clean_line
            or "Diet Plan" in clean_line
            or "Calorie Recommendation" in clean_line
            or "Health Tips" in clean_line
            or "Motivation" in clean_line
        ):
            story.append(Spacer(1, 8))
            story.append(
                Paragraph(
                    clean_line,
                    heading_style
                )
            )
            story.append(Spacer(1, 4))
        else:
            story.append(
                Paragraph(
                    clean_line,
                    body_style
                )
            )

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Generated by FitFusion AI",
            styles["Italic"]
        )
    )

    doc.build(story)

    buffer.seek(0)

    return buffer
